services:
  - type: web
    name: nl2sql-api
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_BASE_URL
        sync: false
      - key: OPENAI_MODEL
        value: azure/gpt-5-mini
      - key: DATA_DIR
        value: /opt/render/project/src/data
